- alias: "Trigger alarm while armed away"
  trigger:
    - platform: state
      entity_id: binary_sensor.door_sensor_contact
      to: "on"
    - platform: state
      entity_id: binary_sensor.tapo_c110_43b0_motion_alarm
      to: "on"
    - platform: state
      entity_id: binary_sensor.tapo_c110_43b0_noise
      to: "on"
  condition:
    - condition: state
      entity_id: alarm_control_panel.home_alarm
      state: armed_away
  action:
    service: alarm_control_panel.alarm_trigger
    target:
      entity_id: alarm_control_panel.home_alarm

- alias: "Send notification when alarm triggered"
  trigger:
    - platform: state
      entity_id: alarm_control_panel.home_alarm
      to: "triggered"
  action:
    - service: telegram_bot.send_photo
      data:
        file: "/media/hallway_last_snapshot.jpg"
        target: [!secret tlg_user1_id, !secret tlg_user2_id, !secret tlg_user5_id]
        caption: Сработала сигнализация!
    - service: notify.alarm
      data:
        title: Охрана
        message: Сработала сигнализация!
        data:
          url: /lovelace/main
          importance: high
          persistent: true
          vibrationPattern: 100, 1000, 100, 1000, 100
          ledColor: red
          image: "/media/local/hallway_last_snapshot.jpg"
          content-type: image
          push:
            sound:
              name: alarm.caf
              critical: 1
              volume: 1
          actions:
            - action: ALARM
              title: Sound Alarm
              destructive: true
              icon: sfsymbols:bell
            - action: SILENCE
              title: Silence Alarm
              icon: sfsymbols:bell.slash
            - action: disarmed
              title: Снять с охраны
              icon: sfsymbols:lock.open

- alias: "Send notification when alarm is Disarmed"
  trigger:
    - platform: state
      entity_id: alarm_control_panel.home_alarm
      not_from: "arming"
      to: "disarmed"
  action:
    - service: notify.mariya_konstantin_ivan
      data:
        message: "ВНИМАНИЕ! Сигнализация отключена."
    - service: switch.turn_on
      entity_id: switch.tapo_c110_43b0_privacy
    - service: switch.turn_off
      entity_id: switch.tapo_c110_43b0_notifications
    - action: select.select_option
      target:
        entity_id: select.tapo_c110_43b0_automatic_alarm
      data:
        option: "off"

- alias: "Send notification when alarm is in pending status"
  trigger:
    - platform: state
      entity_id: alarm_control_panel.home_alarm
      to: "pending"
  action:
    - service: notify.mariya_konstantin_ivan
      data:
        message: "ВНИМАНИЕ! Сигнализация перешла в режим ожидания."
    - service: camera.snapshot
      target:
        entity_id: camera.tapo_c110_43b0_hd_stream
      data:
        filename: "/media/hallway_last_snapshot.jpg"

- id: "Create photos when arming"
  alias: Create photos when arming
  triggers:
    - trigger: state
      entity_id:
        - alarm_control_panel.home_alarm
      to: arming
  actions:
    - action: camera.snapshot
      target:
        entity_id: camera.tapo_c110_43b0_hd_stream
      data:
        filename: "/media/local/hallway_last_snapshot.jpg"

- alias: "Send notification when alarm is Armed in Away mode"
  trigger:
    - platform: state
      entity_id: alarm_control_panel.home_alarm
      to: "armed_away"
  action:
    - service: switch.turn_off
      entity_id: switch.tapo_c110_43b0_privacy
    - service: switch.turn_on
      entity_id: switch.tapo_c110_43b0_notifications
    - action: select.select_option
      target:
        entity_id: select.tapo_c110_43b0_automatic_alarm
      data:
        option: "both"
    - service: telegram_bot.send_photo
      data:
        file: "/media/local/hallway_last_snapshot.jpg"
        target: [!secret tlg_user1_id, !secret tlg_user2_id, !secret tlg_user5_id]
        caption: Сигнализация активирована.

- alias: "Send notification when alarm is Armed in Home mode"
  trigger:
    - platform: state
      entity_id: alarm_control_panel.home_alarm
      to: "armed_home"
  action:
    - service: notify.mariya_konstantin_ivan
      data:
        # Using multi-line notation allows for easier quoting
        message: >
          ВНИМАНИЕ! Сигнализация активирована в режима Дома.
