security:
  script:
    security_activate:
      sequence:
        - service: siren.turn_on
          metadata: {}
          data:
            duration: "1"
          target:
            entity_id: siren.tapo_c110_43b0_siren
        - service: select.select_option
          target:
            entity_id: select.siren_melody
          data:
            option: "15"
        - service: select.select_option
          target:
            entity_id: select.siren_volume
          data:
            option: "high"
        # - service: number.set_value
        #   data:
        #     value: "1"
        #   target:
        #     entity_id: number.siren_duration
        - service: switch.turn_on
          target:
            entity_id: switch.siren_alarm

      # else:
      #   - alias: "security deactivate"
      #     sequence:
      #       - service: siren.turn_on
      #         metadata: {}
      #         data:
      #           duration: "20"
      #         target:
      #           entity_id: siren.tapo_c110_43b0_siren
      #       - service: switch.turn_on
      #         metadata: {}
      #         data: {}
      #         target:
      #           entity_id: switch.siren_alarm

    # - alias: 'security activate'
    #   service: light.turn_on
    #   target:
    #     entity_id: melody 15 1/2
    #   data:
    #     brightness: 100
    # select.siren_volume high
    # number.siren_duration

  automation:
    - id: "automatic arming"
      alias: "automatic arming"
      triggers:
        - trigger: template
          value_template: "{{ states('zone.home') | int == 0 }}"
      condition:
        not:
          - condition: state
            entity_id: alarm_control_panel.home_alarm
            state: "armed_away"
      actions:
        - action: alarm_control_panel.alarm_arm_away
          target:
            entity_id: alarm_control_panel.home_alarm
        - action: script.turn_on
          entity_id: script.light_turn_off_all

    - id: "automatic disarming"
      alias: "automatic disarming"
      triggers:
        - trigger: template
          value_template: "{{ states('zone.home') | int > 0 }}"
      condition:
        not:
          - condition: state
            entity_id: alarm_control_panel.home_alarm
            state: "disarmed"
      actions:
        - action: alarm_control_panel.alarm_disarm
          target:
            entity_id: alarm_control_panel.home_alarm

    - id: "Actions when arming"
      alias: Actions when arming
      triggers:
        - trigger: state
          entity_id:
            - alarm_control_panel.home_alarm
          to: arming
      actions:
        - action: switch.turn_off
          entity_id: switch.tapo_c110_43b0_privacy
        - action: switch.turn_on
          entity_id: switch.tapo_c110_43b0_notifications
        # - action: select.select_option
        #   target:
        #     entity_id: select.tapo_c110_43b0_automatic_alarm
        #   data:
        #     option: "both"
        - delay: 5
        - action: camera.snapshot
          data:
            filename: /media/hallway_last_snapshot.jpg
          target:
            entity_id: camera.tapo_c110_43b0_hd_stream

    - alias: "Actions when alarm is Armed in Away mode"
      triggers:
        - trigger: state
          entity_id: alarm_control_panel.home_alarm
          to: "armed_away"
      actions:
        - action: telegram_bot.send_photo
          data:
            file: "/media/hallway_last_snapshot.jpg"
            target:
              [!secret tlg_user1_id, !secret tlg_user2_id, !secret tlg_user5_id]
            caption: Сигнализация активирована.
            disable_notification: true
        - action: notify.alarm
          data:
            title: Охрана
            message: Квартира поставлена на охрану.
            data:
              url: /lovelace/main
              importance: high
              persistent: true
              image: "/media/local/hallway_last_snapshot.jpg"
              content-type: image

    - alias: "Actions when alarm is Armed in Home mode"
      triggers:
        - trigger: state
          entity_id: alarm_control_panel.home_alarm
          to: "armed_home"
      actions:
        - action: telegram_bot.send_message
          data:
            disable_notification: true
            target:
              [!secret tlg_user1_id, !secret tlg_user2_id, !secret tlg_user5_id]
            message: Сигнализация активирована в режима Дома.
            title: Охрана
        - action: notify.alarm
          data:
            title: Охрана
            message: Сигнализация активирована в режима Дома.
            data:
              url: /lovelace/main

    - alias: "Trigger alarm while armed away"
      triggers:
        - trigger: state
          entity_id: binary_sensor.door_sensor_contact
          to: "on"
        - trigger: state
          entity_id: binary_sensor.tapo_c110_43b0_motion_alarm
          to: "on"
        - trigger: state
          entity_id: binary_sensor.tapo_c110_43b0_noise
          to: "on"
      condition:
        - condition: state
          entity_id: alarm_control_panel.home_alarm
          state: armed_away
      actions:
        action: alarm_control_panel.alarm_trigger
        target:
          entity_id: alarm_control_panel.home_alarm

    - alias: "Actions when alarm is in pending status"
      triggers:
        - trigger: state
          entity_id: alarm_control_panel.home_alarm
          to: "pending"
      actions:
        - action: camera.snapshot
          target:
            entity_id: camera.tapo_c110_43b0_hd_stream
          data:
            filename: "/media/hallway_last_snapshot.jpg"
        - delay: 2
        - action: telegram_bot.send_photo
          data:
            file: "/media/hallway_last_snapshot.jpg"
            caption: Сигнализация перешла в режим ожидания
            target:
              [!secret tlg_user1_id, !secret tlg_user2_id, !secret tlg_user5_id]
        - action: notify.alarm
          data:
            title: Охрана
            message: Сигнализация перешла в режим ожидания!
            data:
              url: /lovelace/main
              importance: high
              persistent: true
              vibrationPattern: 100, 1000, 100, 1000, 100
              ledColor: red
              image: "/media/local/hallway_last_snapshot.jpg"
              content-type: image
              push:
                sound:
                  name: alarm.caf
                  critical: 1
                  volume: 0.75
              actions:
                - action: ALARM
                  title: Sound Alarm
                  destructive: true
                  icon: sfsymbols:bell
                - action: SILENCE
                  title: Silence Alarm
                  icon: sfsymbols:bell.slash
                - action: disarmed
                  title: Снять с охраны
                  icon: sfsymbols:lock.open

    - alias: "disarmed"
      triggers:
        - trigger: event
          event_type: mobile_app_notification_action
          event_data:
            action: "disarmed"
      actions:
        - action: alarm_control_panel.alarm_disarm
          target:
            entity_id: alarm_control_panel.home_alarm

    - alias: "Send notification when alarm triggered"
      triggers:
        - trigger: state
          entity_id: alarm_control_panel.home_alarm
          to: "triggered"
      actions:
        - action: camera.snapshot
          target:
            entity_id: camera.tapo_c110_43b0_hd_stream
          data:
            filename: "/media/hallway_last_snapshot.jpg"
        - delay: 2
        - action: telegram_bot.send_photo
          data:
            file: "/media/hallway_last_snapshot.jpg"
            target:
              [!secret tlg_user1_id, !secret tlg_user2_id, !secret tlg_user5_id]
            caption: Сработала сигнализация!
        - action: notify.alarm
          data:
            title: Охрана
            message: Сработала сигнализация!
            data:
              url: /lovelace/main
              importance: high
              persistent: true
              vibrationPattern: 100, 1000, 100, 1000, 100
              ledColor: red
              image: "/media/local/hallway_last_snapshot.jpg"
              content-type: image
              push:
                sound:
                  name: alarm.caf
                  critical: 1
                  volume: 1
              actions:
                - action: ALARM
                  title: Sound Alarm
                  destructive: true
                  icon: sfsymbols:bell
                - action: SILENCE
                  title: Silence Alarm
                  icon: sfsymbols:bell.slash
                - action: disarmed
                  title: Снять с охраны
                  icon: sfsymbols:lock.open

    - alias: "Actions when alarm is Disarmed"
      triggers:
        - trigger: state
          entity_id: alarm_control_panel.home_alarm
          not_from: "arming"
          to: "disarmed"
      actions:
        - action: telegram_bot.send_message
          data:
            disable_notification: true
            target:
              [!secret tlg_user1_id, !secret tlg_user2_id, !secret tlg_user5_id]
            message: Квартира снята с охраны.
            title: Охрана
        - action: notify.alarm
          data:
            title: "Охрана"
            message: Квартира снята с охраны.
            data:
              url: "/lovelace/main"
              importance: high
              persistent: true
        - action: switch.turn_on
          entity_id: switch.tapo_c110_43b0_privacy
        - action: switch.turn_off
          entity_id: switch.tapo_c110_43b0_notifications
        - action: select.select_option
          target:
            entity_id: select.tapo_c110_43b0_automatic_alarm
          data:
            option: "off"
