security:
  script:
    security_activate:
      sequence:
        - service: siren.turn_on
          metadata: {}
          data:
            duration: "1"
          target:
            entity_id: siren.tapo_c110_43b0_siren
        - service: select.select_option
          target:
            entity_id: select.siren_melody
          data:
            option: "15"
        - service: select.select_option
          target:
            entity_id: select.siren_volume
          data:
            option: "high"
        # - service: number.set_value
        #   data:
        #     value: "1"
        #   target:
        #     entity_id: number.siren_duration
        - service: switch.turn_on
          target:
            entity_id: switch.siren_alarm

      # else:
      #   - alias: "security deactivate"
      #     sequence:
      #       - service: siren.turn_on
      #         metadata: {}
      #         data:
      #           duration: "20"
      #         target:
      #           entity_id: siren.tapo_c110_43b0_siren
      #       - service: switch.turn_on
      #         metadata: {}
      #         data: {}
      #         target:
      #           entity_id: switch.siren_alarm

    # - alias: 'security activate'
    #   service: light.turn_on
    #   target:
    #     entity_id: melody 15 1/2
    #   data:
    #     brightness: 100
    # select.siren_volume high
    # number.siren_duration

  automation:
    - id: "automatic arming"
      alias: "automatic arming"
      trigger:
        - platform: template
          value_template: "{{ states('zone.home') | int == 0 }}"
      condition:
        not:
          - condition: state
            entity_id: alarm_control_panel.home_alarm
            state: "armed_away"
      action:
        - service: alarm_control_panel.alarm_arm_away
          target:
            entity_id: alarm_control_panel.home_alarm
        - service: script.turn_on
          entity_id: script.light_turn_off_all

    - id: "automatic disarming"
      alias: "automatic disarming"
      trigger:
        - platform: template
          value_template: "{{ states('zone.home') | int > 0 }}"
      condition:
        not:
          - condition: state
            entity_id: alarm_control_panel.home_alarm
            state: "disarmed"
      action:
        - service: alarm_control_panel.alarm_disarm
          target:
            entity_id: alarm_control_panel.home_alarm

    - id: "alarm notify armed"
      alias: "alarm notify armed"
      trigger:
        - platform: state
          entity_id: alarm_control_panel.home_alarm
          to:
            - "armed_away"
      action:
        - service: notify.mobile_app_artemevk
          data:
            title: "Охрана"
            message: Квартира поставлена на охрану.
            data:
              url: "/lovelace/main"

    - id: "alarm notify disarmed"
      alias: "alarm notify disarmed"
      trigger:
        - platform: state
          entity_id: alarm_control_panel.home_alarm
          not_from:
            - "arming"
            - "armed_home"
          to:
            - "disarmed"
      action:
        - service: notify.mobile_app_artemevk
          data:
            title: "Охрана"
            message: Квартира снята с охраны.
            data:
              url: "/lovelace/main"
