security:
  script:

    security_activate:
      sequence:
        - service: siren.turn_on
          metadata: {}
          data:
            duration: "1"
          target:
            entity_id: siren.tapo_c110_43b0_siren
        - service: select.select_option
          target:
            entity_id: select.siren_melody
          data:
            option: "15"
        - service: select.select_option
          target:
            entity_id: select.siren_volume
          data:
            option: "high"
        # - service: number.set_value
        #   data:
        #     value: "1"
        #   target:
        #     entity_id: number.siren_duration
        - service: switch.turn_on
          target:
            entity_id: switch.siren_alarm

      # else:
      #   - alias: "security deactivate"
      #     sequence:
      #       - service: siren.turn_on
      #         metadata: {}
      #         data:
      #           duration: "20"
      #         target:
      #           entity_id: siren.tapo_c110_43b0_siren
      #       - service: switch.turn_on
      #         metadata: {}
      #         data: {}
      #         target:
      #           entity_id: switch.siren_alarm


    # - alias: 'security activate'
    #   service: light.turn_on
    #   target:
    #     entity_id: melody 15 1/2
    #   data:
    #     brightness: 100
    # select.siren_volume high
    # number.siren_duration