- platform: group
  name: "Childrens_room_ceiling_lamp"
  entities:
    - light.yeelight_s1_child_1
    - light.yeelight_s1_child_2
    - light.yeelight_s1_child_3
    - light.yeelight_s1_child_4
    - light.yeelight_s1_child_5
    - light.yeelight_s1_child_6